\c tech_challenge

CREATE TABLE IF NOT EXISTS DEMO (
  SEQN int,
  SDDSRVYR int,
  RIDSTATR int,
  RIAGENDR int,
  RIDAGEYR decimal,
  RIDAGEMN decimal,
  RIDRETH1 int,
  RIDRETH3 int,
  RIDEXMON int,
  RIDEXAGM decimal,
  DMQMILIZ int,
  DMQADFC int,
  DMDBORN4 int,
  DMDCITZN int,
  DMDYRSUS int,
  DMDEDUC3 decimal,
  DMDEDUC2 int,
  DMDMARTL int,
  RIDEXPRG int,
  SIALANG int,
  SIAPROXY int,
  SIAINTRP int,
  FIALANG int,
  FIAPROXY int,
  FIAINTRP int,
  MIALANG int,
  MIAPROXY int,
  MIAINTRP int,
  AIALANGA int,
  DMDHHSIZ int,
  DMDFMSIZ int,
  DMDHHSZA int,
  DMDHHSZB int,
  DMDHHSZE int,
  DMDHRGND int,
  DMDHRAGZ int,
  DMDHREDZ int,
  DMDHRMAZ int,
  DMDHSEDZ int,
  WTINT2YR double precision,
  WTMEC2YR double precision,
  SDMVPSU int,
  SDMVSTRA int,
  INDHHIN2 int,
  INDFMIN2 int,
  INDFMPIR double precision,
  PRIMARY KEY (SEQN)
) ;

CREATE TABLE IF NOT EXISTS DR1IFF (
  SEQN int,
  WTDRD1 double precision,
  WTDR2D double precision,
  DR1ILINE int,
  DR1DRSTZ int,
  DR1EXMER int,
  DRABF int,
  DRDINT int,
  DR1DBIH decimal,
  DR1DAY int,
  DR1LANG int,
  DR1CCMNM decimal,
  DR1CCMTX decimal,
  DR1_020 decimal,
  DR1_030Z int,
  DR1FS int,
  DR1_040Z int,
  DR1IFDCD int,
  DR1IGRMS decimal,
  DR1IKCAL decimal,
  DR1IPROT decimal,
  DR1ICARB decimal,
  DR1ISUGR decimal,
  DR1IFIBE decimal,
  DR1ITFAT decimal,
  DR1ISFAT decimal,
  DR1IMFAT decimal,
  DR1IPFAT decimal,
  DR1ICHOL decimal,
  DR1IATOC decimal,
  DR1IATOA decimal,
  DR1IRET decimal,
  DR1IVARA decimal,
  DR1IACAR decimal,
  DR1IBCAR decimal,
  DR1ICRYP decimal,
  DR1ILYCO decimal,
  DR1ILZ decimal,
  DR1IVB1 decimal,
  DR1IVB2 decimal,
  DR1INIAC decimal,
  DR1IVB6 decimal,
  DR1IFOLA decimal,
  DR1IFA decimal,
  DR1IFF decimal,
  DR1IFDFE decimal,
  DR1ICHL decimal,
  DR1IVB12 decimal,
  DR1IB12A decimal,
  DR1IVC decimal,
  DR1IVD decimal,
  DR1IVK decimal,
  DR1ICALC decimal,
  DR1IPHOS decimal,
  DR1IMAGN decimal,
  DR1IIRON decimal,
  DR1IZINC decimal,
  DR1ICOPP decimal,
  DR1ISODI decimal,
  DR1IPOTA decimal,
  DR1ISELE decimal,
  DR1ICAFF decimal,
  DR1ITHEO decimal,
  DR1IALCO decimal,
  DR1IMOIS decimal,
  DR1IS040 decimal,
  DR1IS060 decimal,
  DR1IS080 decimal,
  DR1IS100 decimal,
  DR1IS120 decimal,
  DR1IS140 decimal,
  DR1IS160 decimal,
  DR1IS180 decimal,
  DR1IM161 decimal,
  DR1IM181 decimal,
  DR1IM201 decimal,
  DR1IM221 decimal,
  DR1IP182 decimal,
  DR1IP183 decimal,
  DR1IP184 decimal,
  DR1IP204 decimal,
  DR1IP205 decimal,
  DR1IP225 decimal,
  DR1IP226 decimal,
  PRIMARY KEY (SEQN, DR1ILINE)
);

\l
\c tech_challenge
\d demographics
\d dietry_individual_foods_first_day